version: "3.8"
services:
  ta-db:
    image: mysql:5.7
    container_name: ta-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ta-db
    volumes:
      - mysql_data:/var/lib/mysql

  ta-be:
    image: ta-be
    container_name: ta-be
    ports:
      - "8000:8000"
    environment:
      - MYSQL_SERVER=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MYSQL_DB=ta-db
      - BACKEND_CORS_ORIGINS=["*", "http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080"]
    depends_on:
      - ta-db

volumes:
  mysql:
