"""create kecamatan, kelurahan, patients, and tb_cases models

Revision ID: 1ad262b9d243
Revises: e46a0dac7f60
Create Date: 2023-11-05 11:43:23.028245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ad262b9d243'
down_revision: Union[str, None] = 'e46a0dac7f60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
