"""create kecamatan, kelurahan, patients, and tb_cases models

Revision ID: e46a0dac7f60
Revises: 5e345f41500a
Create Date: 2023-11-05 11:39:20.736277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e46a0dac7f60'
down_revision: Union[str, None] = '5e345f41500a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kecamatan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kecamatan_id'), 'kecamatan', ['id'], unique=False)
    op.create_index(op.f('ix_kecamatan_name'), 'kecamatan', ['name'], unique=True)
    op.create_table('kelurahan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('kecamatan_id', sa.Integer(), nullable=True),
    sa.Column('puskesmas_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['kecamatan_id'], ['kecamatan.id'], ),
    sa.ForeignKeyConstraint(['puskesmas_id'], ['puskesmas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kelurahan_id'), 'kelurahan', ['id'], unique=False)
    op.create_index(op.f('ix_kelurahan_name'), 'kelurahan', ['name'], unique=True)
    op.create_table('patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(length=255), nullable=False),
    sa.Column('addr_kota', sa.String(length=255), nullable=False),
    sa.Column('addr_kecamatan', sa.String(length=255), nullable=False),
    sa.Column('kecamatan_id', sa.Integer(), nullable=True),
    sa.Column('addr_kelurahan', sa.String(length=255), nullable=False),
    sa.Column('kelurahan_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['kecamatan_id'], ['kecamatan.id'], ),
    sa.ForeignKeyConstraint(['kelurahan_id'], ['kelurahan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patients_addr_kecamatan'), 'patients', ['addr_kecamatan'], unique=False)
    op.create_index(op.f('ix_patients_addr_kelurahan'), 'patients', ['addr_kelurahan'], unique=False)
    op.create_index(op.f('ix_patients_addr_kota'), 'patients', ['addr_kota'], unique=False)
    op.create_index(op.f('ix_patients_age'), 'patients', ['age'], unique=False)
    op.create_index(op.f('ix_patients_gender'), 'patients', ['gender'], unique=False)
    op.create_index(op.f('ix_patients_id'), 'patients', ['id'], unique=False)
    op.create_table('tb_cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('puskesmas_id', sa.Integer(), nullable=True),
    sa.Column('patients_id', sa.Integer(), nullable=True),
    sa.Column('diagnosis', sa.String(length=255), nullable=False),
    sa.Column('anatomy', sa.String(length=255), nullable=False),
    sa.Column('is_new', sa.Boolean(), nullable=False),
    sa.Column('is_dm', sa.Boolean(), nullable=False),
    sa.Column('is_hiv', sa.Boolean(), nullable=False),
    sa.Column('treatment_status', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.Date(), nullable=False),
    sa.Column('updated_at', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['patients_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['puskesmas_id'], ['puskesmas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tb_cases_anatomy'), 'tb_cases', ['anatomy'], unique=False)
    op.create_index(op.f('ix_tb_cases_created_at'), 'tb_cases', ['created_at'], unique=False)
    op.create_index(op.f('ix_tb_cases_diagnosis'), 'tb_cases', ['diagnosis'], unique=False)
    op.create_index(op.f('ix_tb_cases_id'), 'tb_cases', ['id'], unique=False)
    op.create_index(op.f('ix_tb_cases_is_dm'), 'tb_cases', ['is_dm'], unique=False)
    op.create_index(op.f('ix_tb_cases_is_hiv'), 'tb_cases', ['is_hiv'], unique=False)
    op.create_index(op.f('ix_tb_cases_is_new'), 'tb_cases', ['is_new'], unique=False)
    op.create_index(op.f('ix_tb_cases_treatment_status'), 'tb_cases', ['treatment_status'], unique=False)
    op.create_index(op.f('ix_tb_cases_updated_at'), 'tb_cases', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tb_cases_updated_at'), table_name='tb_cases')
    op.drop_index(op.f('ix_tb_cases_treatment_status'), table_name='tb_cases')
    op.drop_index(op.f('ix_tb_cases_is_new'), table_name='tb_cases')
    op.drop_index(op.f('ix_tb_cases_is_hiv'), table_name='tb_cases')
    op.drop_index(op.f('ix_tb_cases_is_dm'), table_name='tb_cases')
    op.drop_index(op.f('ix_tb_cases_id'), table_name='tb_cases')
    op.drop_index(op.f('ix_tb_cases_diagnosis'), table_name='tb_cases')
    op.drop_index(op.f('ix_tb_cases_created_at'), table_name='tb_cases')
    op.drop_index(op.f('ix_tb_cases_anatomy'), table_name='tb_cases')
    op.drop_table('tb_cases')
    op.drop_index(op.f('ix_patients_id'), table_name='patients')
    op.drop_index(op.f('ix_patients_gender'), table_name='patients')
    op.drop_index(op.f('ix_patients_age'), table_name='patients')
    op.drop_index(op.f('ix_patients_addr_kota'), table_name='patients')
    op.drop_index(op.f('ix_patients_addr_kelurahan'), table_name='patients')
    op.drop_index(op.f('ix_patients_addr_kecamatan'), table_name='patients')
    op.drop_table('patients')
    op.drop_index(op.f('ix_kelurahan_name'), table_name='kelurahan')
    op.drop_index(op.f('ix_kelurahan_id'), table_name='kelurahan')
    op.drop_table('kelurahan')
    op.drop_index(op.f('ix_kecamatan_name'), table_name='kecamatan')
    op.drop_index(op.f('ix_kecamatan_id'), table_name='kecamatan')
    op.drop_table('kecamatan')
    # ### end Alembic commands ###
